image: 10.100.98.41:5000/maao-docker/maao-simple:11.0-maao

variables:
    SERIES_BRANCH: '11.0'
    POSTGRES_USER: odoo
    POSTGRES_PASSWORD: odoo

    ODOO_DB_HOST: 10.100.98.41-maao-docker-maao-ci-postgres
    ODOO_DB_USER: odoo
    ODOO_DB_PASSWORD: odoo
    ODOO_ADMIN_PASS: admin

    PIP_CACHE_DIR: ".hidden-pip-cache"

cache:
    paths:
        - ".hidden-pip-cache"


before_script:
    - pwd
    - whoami
    - python --version
    - odoo-helper --version
    - odoo-helper exec jshint --version
    - cat /opt/odoo/conf/odoo.conf
    - odoo-helper exec pylint --version
    - odoo-helper exec flake8 --version

flake8:
    script:
        - odoo-helper test flake8 .

pylint:
    script:
        - odoo-helper test pylint .

tests:
    services:
        - 10.100.98.41:5000/maao-docker/maao-ci-postgres

    before_script:
        - odoo-helper link .
    script:
        - odoo-helper --use-unbuffer test --coverage --create-test-db -d .
        - odoo-helper exec coverage report --fail-under=90
        - odoo-helper exec coverage html -d html-coverage
    coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)/'
    artifacts:
        paths:
            - html-coverage

migration_tests:
    variables:
        ODOO_DB_NAME: test-db

    services:
        - 10.100.98.41:5000/maao-docker/maao-ci-postgres

    before_script:
        - git checkout $SERIES_BRANCH
        - git pull
        - odoo-helper link .
        - odoo-helper --use-unbuffer db create --demo $ODOO_DB_NAME
        - odoo-helper --use-unbuffer addons install -d $ODOO_DB_NAME $(odoo-helper addons list .)
        - git checkout $CI_COMMIT_SHA
        - odoo-helper link .
        - odoo-helper --use-unbuffer addons update-list
        - odoo-helper --use-unbuffer addons update -d $ODOO_DB_NAME $(odoo-helper addons list .)
    script:
        - odoo-helper --use-unbuffer test --coverage -d .
        - odoo-helper exec coverage report --fail-under=90
    coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)/'
    only:
        - /^11.0-.*$/   # only branches that started with '11.0-'
