variables:
    SERIES_BRANCH: '11.0'
    ODOO_ADMIN_PASS: admin

cache:
    paths:
        - "$HOME/.cache/pip"

stages:
    - static-test
    - test
    - translation

build_env:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:11.0-simple
    stage: static-test
    script:
        - pwd
        - whoami
        - python --version
        - odoo-helper --version
        - odoo-helper status --tools-versions --ci-tools-versions

flake8:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:11.0-simple
    stage: static-test
    script:
        - odoo-helper test flake8 .

pylint:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:11.0-simple
    stage: static-test
    script:
        - odoo-helper test pylint .

bandit:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:11.0-simple
    stage: static-test
    before_script:
        - odoo-helper pip install bandit
    script:
        - odoo-helper exec bandit -r .

stylelint:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:11.0-simple
    stage: static-test
    script:
        - odoo-helper lint style .

check-versions:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:11.0-simple
    stage: static-test
    script:
        - odoo-helper ci check-versions-git --repo-version . origin/$SERIES_BRANCH $CI_COMMIT_SHA
    only:
        - /^11.0-.*$/   # only branches that started with '11.0-'

tests:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:11.0-ci
    stage: test
    before_script:
        - odoo-helper link .
    script:
        - odoo-helper --use-unbuffer test --coverage --create-test-db -d .
        - odoo-helper exec coverage report --fail-under=90
        - odoo-helper exec coverage html -d html-coverage
    coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)/'

migration_tests:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:11.0-ci
    stage: test
    variables:
        ODOO_DB_NAME: test-db
    before_script:
        - git checkout $SERIES_BRANCH
        - git pull
        - odoo-helper link .
        - odoo-helper --use-unbuffer db create --demo $ODOO_DB_NAME
        - odoo-helper --use-unbuffer addons install -d $ODOO_DB_NAME $(odoo-helper addons list .)
        - git checkout $CI_COMMIT_SHA
        - odoo-helper link .
        - odoo-helper --use-unbuffer addons update-list
        - odoo-helper --use-unbuffer addons update -d $ODOO_DB_NAME $(odoo-helper addons list .)
    script:
        - odoo-helper --use-unbuffer test --coverage -d .
        - odoo-helper exec coverage report --fail-under=90
    coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)/'
    only:
        - /^11.0-.*$/   # only branches that started with '11.0-'

translation_rate_ua:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:11.0-ci
    stage: translation 
    before_script:
        - odoo-helper link .
    script:
        - odoo-helper --use-unbuffer tr rate --lang uk_UA --min-total-rate 70 $(odoo-helper addons list .)
    coverage: '/^TOTAL\s+\|\s+\d+\s+\|\s+\d+\s+|\s+(\d+\.\d+)/'
